version: "3"

vars:
  ros_setup: /opt/ros/humble/setup.sh
  nr: 5
  r: 5
  comm_file: /workspaces/src/imesa-experiments/experiments/config/communication_models/pairwise.json
  LD_LIBRARY_PATH: /workspaces/src/g2o/install/lib:/workspaces/src/ORB_SLAM3/Thirdparty/DBoW2/lib:/usr/local/lib
  experiment_dir: /workspaces/src/imesa-experiments/data

includes:
  raido:
    taskfile: ../raido_imesa_experiments/Taskfile.yaml
    dir: ../raido_imesa_experiments

tasks:
  build:
    deps: [raido:build]
    cmds:
      - cmake --preset default
      - source /opt/ros/humble/setup.sh && cmake --build --preset default-build

  build-debug:
    deps: [raido:build-debug]
    cmds:
      - cmake --preset config-debug
      - source /opt/ros/humble/setup.sh && cmake --build --preset build-debug

  run-trial:
    cmds:
      - build/experiments/run-trial

  generate-2d:
    cmds:
      - experiments/scripts/make-multi-robot-dataset-2d -o /workspaces/src/imesa-experiments/data/datasets/2d_5r -n 2d -nr 5 -r {{.r}} --xlims -50 50 --ylims -50 50
      - experiments/scripts/make-multi-robot-dataset-2d -o /workspaces/src/imesa-experiments/data/datasets/2d_10r -n 2d -nr 10 -r {{.r}} --xlims -50 50 --ylims -50 50
  
  generate-2d-noise:
    cmds:
      - experiments/scripts/make-multi-robot-dataset-2d -o /workspaces/src/imesa-experiments/data/datasets/2d_10r_{{.noise}} -n 2d -nr 10 -r {{.r}} --xlims -50 50 --ylims -50 50 --noised_zeros 1 --robot_zero_prior_noise_sigmas {{.noise}} {{.noise}} 1

  generate-2d-random:
    cmds:
      - experiments/scripts/make-multi-robot-dataset-2d -o /workspaces/src/imesa-experiments/data/datasets/2d_10r_random_origin -n 2d -nr 10 -r {{.r}} --xlims -50 50 --ylims -50 50 --noised_zeros 2

  run-raido:
    cmds:
      - source {{.ros_setup}} && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{{.LD_LIBRARY_PATH}}" build/experiments/run-trial -d {{.data_file}} -m raido -p {{.param_file}} -o {{.output_dir}} -r 10 -s 0 -t POSE2 -c {{.comm_file}}
    vars:
      data_file: /workspaces/src/imesa-experiments/data/datasets/2d_5r_noised_prior/01_0000.jrl
      output_dir: /workspaces/src/imesa-experiments/outputs
      param_file: /workspaces/src/raido_imesa_experiments/config/raido.json

  plot-mean-residuals:
    cmds:
      - experiments/scripts/plot-mean-residual -d {{.data_file}} -r {{.output_dir}}
    vars:
      data_file: /workspaces/src/imesa-experiments/data/2d_5robots_0000.jrl
      output_dir: /workspaces/src/imesa-experiments/outputs/2d_5robots_0000_RaiDO_2024-08-21_11-30-25

  run-all:
    cmds:
      - source {{.ros_setup}} && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{{.LD_LIBRARY_PATH}}" experiments/scripts/run-experiment -d {{.experiment_dir}} -iv {{.iv}} -m {{.methods}} -p {{.method_configs}} -n 4 -c {{.comm_file}}
    vars:
      iv: >-
        2d_nr
      methods: >-
        raido
        imesa
        centralized
        independent
        ddfsam2
      config_dir: /workspaces/src/imesa-experiments/experiments/config/methods
      method_configs: >-
        /workspaces/src/raido_imesa_experiments/config/raido.json
        {{.config_dir}}/imesa.json
        {{.config_dir}}/independent.json
        {{.config_dir}}/independent.json
        {{.config_dir}}/ddfsam2.json

  summarize-experiment:
    cmds:
      - experiments/scripts/summarize-experiment -l -n {{.experiment_name}} -d {{.dataset_dir}} -r {{.result_dir}} -iv {{.iv}} -ivl {{.ivl}} -m {{.all_methods}} -x {{.xlabel}}
    vars:
      experiment_name: 2D
      dataset_dir: "{{.experiment_dir}}/datasets"
      result_dir: "{{.experiment_dir}}/results"
      iv: >-
        2d_5r_gt_prior
        2d_5r_zero_prior
        2d_5r_noised_prior
        2d_nr
      ivl: >-
        "GT Prior"
        "Local Prior"
        "Noised Prior"
        "NR"
      all_methods: >-
        raido
        imesa
        centralized
        independent
        ddfsam2

      xlabel: "methods"

